// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIp80FchPCMKAHvfzUGV8Xk1eYE6mFWVU',
    appId: '1:1012395202694:web:6d77ab574ad4c7fe5d9907',
    messagingSenderId: '1012395202694',
    projectId: 'opthadoc-8bfea',
    authDomain: 'opthadoc-8bfea.firebaseapp.com',
    storageBucket: 'opthadoc-8bfea.appspot.com',
    measurementId: 'G-KS6ZT637WS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoPHKjNpPjWF3_2R2x6oybL-W_vb8JjPk',
    appId: '1:1012395202694:android:986b6fb8820a0e755d9907',
    messagingSenderId: '1012395202694',
    projectId: 'opthadoc-8bfea',
    storageBucket: 'opthadoc-8bfea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBoEcx4orOwWlfByZMyCrgLySRb36Sd6o',
    appId: '1:1012395202694:ios:fbc38d382dd226e65d9907',
    messagingSenderId: '1012395202694',
    projectId: 'opthadoc-8bfea',
    storageBucket: 'opthadoc-8bfea.appspot.com',
    iosBundleId: 'com.example.opthaDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBoEcx4orOwWlfByZMyCrgLySRb36Sd6o',
    appId: '1:1012395202694:ios:fbc38d382dd226e65d9907',
    messagingSenderId: '1012395202694',
    projectId: 'opthadoc-8bfea',
    storageBucket: 'opthadoc-8bfea.appspot.com',
    iosBundleId: 'com.example.opthaDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIp80FchPCMKAHvfzUGV8Xk1eYE6mFWVU',
    appId: '1:1012395202694:web:8f67d612940c38025d9907',
    messagingSenderId: '1012395202694',
    projectId: 'opthadoc-8bfea',
    authDomain: 'opthadoc-8bfea.firebaseapp.com',
    storageBucket: 'opthadoc-8bfea.appspot.com',
    measurementId: 'G-02Z9QW4GYD',
  );
}
